package db.entities;

// Generated 18 ��� 2012 11:03:54 �� by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Cacheable;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

import com.tooooolazy.gwt.widgets.shared.SelectItem;
import com.tooooolazy.util.Messages;

import db.enums.StatusEnum;

/**
 * County generated by hbm2java
 */
@Entity
@Table(name = "counties")
@BatchSize(size=50)
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
public class County implements java.io.Serializable, SelectItem {

	private Integer id;
	private User userByEdUserId;
	private User userByCrUserId;
	private Label label;
	private Country country;
	private String county;
	private String pcFrom;
	private String pcTo;
	private Date crDate;
	private Date edDate;
	private Set<City> cities = new HashSet<City>(0);
	private County aliasFor;
	private StatusEnum status;

	public County() {
	}

	public County(Country country, Date crDate) {
		this.country = country;
		this.crDate = crDate;
	}

	public County(User userByEdUserId, User userByCrUserId, Label label, Country country, String county, String pcFrom, String pcTo, Date crDate,
			Date edDate, Set<City> cities) {
		this.userByEdUserId = userByEdUserId;
		this.userByCrUserId = userByCrUserId;
		this.label = label;
		this.country = country;
		this.county = county;
		this.pcFrom = pcFrom;
		this.pcTo = pcTo;
		this.crDate = crDate;
		this.edDate = edDate;
		this.cities = cities;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ed_user_id")
	public User getUserByEdUserId() {
		return this.userByEdUserId;
	}

	public void setUserByEdUserId(User userByEdUserId) {
		this.userByEdUserId = userByEdUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cr_user_id")
	public User getUserByCrUserId() {
		return this.userByCrUserId;
	}

	public void setUserByCrUserId(User userByCrUserId) {
		this.userByCrUserId = userByCrUserId;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "label_id")
	public Label getLabel() {
		return this.label;
	}

	public void setLabel(Label label) {
		this.label = label;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "country_alpha2_code", nullable = false)
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "county", length = 50)
	public String getCounty() {
		return this.county;
	}

	public void setCounty(String county) {
		this.county = county;
	}

	@Column(name = "pc_from", length = 15)
	public String getPcFrom() {
		return this.pcFrom;
	}

	public void setPcFrom(String pcFrom) {
		this.pcFrom = pcFrom;
	}

	@Column(name = "pc_to", length = 15)
	public String getPcTo() {
		return this.pcTo;
	}

	public void setPcTo(String pcTo) {
		this.pcTo = pcTo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cr_date", nullable = false, length = 19)
	public Date getCrDate() {
		return this.crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ed_date", length = 19)
	public Date getEdDate() {
		return this.edDate;
	}

	public void setEdDate(Date edDate) {
		this.edDate = edDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "county")
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

	@OneToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "alias_id", nullable = true)
	public County getAliasFor() {
		return this.aliasFor;
	}

	public void setAliasFor(County aliasFor) {
		this.aliasFor = aliasFor;
	}

	@Column(name = "status")
	public StatusEnum getStatus() {
		return this.status;
	}

	public void setStatus(StatusEnum status) {
		this.status = status;
	}

	@Override
	@Transient
	public Object getPK() {
		return getId();
	}

	@Override
	@Transient
	public boolean hasLangDefined(String lang) {
		if (getLabel() != null) {
			for (LabelML ml : getLabel().getLabelMLs()) {
				if (ml.getLanguage().getLanguage().equals(lang))
					return true;
			}
		}
		return false;
	}
	@Override
	@Transient
	public String getDisplayValue(String lang) {
		if (getLabel() != null) {
			return getLabel().getDisplayValue(lang);
		}
		return getDefaultValue();
	}
	@Override
	@Transient
	public String getDefaultValue() {
		return getCounty();
	}

	public String toString() {
		String s = getDisplayValue(Messages.getLang());
		if (s == null)
			s = getDefaultValue();
		return s;
	}
}
