package db.entities;

// Generated 13 ��� 2012 12:23:51 �� by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * LabelMLId generated by hbm2java
 */
@Embeddable
public class LabelMLId implements java.io.Serializable {

	private int labelId;
	private int langId;

	public LabelMLId() {
	}

	public LabelMLId(int labelId, int langId) {
		this.labelId = labelId;
		this.langId = langId;
	}

	@Column(name = "label_id", nullable = false)
	public int getLabelId() {
		return this.labelId;
	}

	public void setLabelId(int labelId) {
		this.labelId = labelId;
	}

	@Column(name = "lang_id", nullable = false)
	public int getLangId() {
		return this.langId;
	}

	public void setLangId(int langId) {
		this.langId = langId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof LabelMLId))
			return false;
		LabelMLId castOther = (LabelMLId) other;

		return (this.getLabelId() == castOther.getLabelId()) && (this.getLangId() == castOther.getLangId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getLabelId();
		result = 37 * result + this.getLangId();
		return result;
	}

	public String toString() {
		return labelId + ": " + langId;
	}
}
