package db.entities;

// Generated 21 ��� 2012 12:09:39 �� by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.NotNull;

import com.tooooolazy.gwt.widgets.shared.SelectItem;
import com.tooooolazy.gwt.widgets.shared.SupportedLanguage;
import com.tooooolazy.util.bean.annotations.TlzHidden;

/**
 * Language generated by hbm2java
 */
@Entity
@Table(name = "languages")
public class Language implements java.io.Serializable, SupportedLanguage, SelectItem {

	private Integer id;
	private String langshort;
	private String langlong;
	private Date crDate;
	private Date edDate;
	private String language;
	private Set<Country> countries = new HashSet<Country>(0);
	private Set<User> users = new HashSet<User>(0);
	private Set<LabelML> labelMLs = new HashSet<LabelML>(0);

	public Language() {
	}

	public Language(String langshort, String langlong, Date crDate) {
		this.langshort = langshort;
		this.langlong = langlong;
		this.crDate = crDate;
	}
	public Language(String langshort, String langlong, Date crDate, String language) {
		this.langshort = langshort;
		this.langlong = langlong;
		this.crDate = crDate;
		this.language = language;
	}

	public Language(String langshort, String langlong, Date crDate, Date edDate, String language, Set<Country> countries,
			Set<User> users, Set<LabelML> labelMLs) {
		this.langshort = langshort;
		this.langlong = langlong;
		this.crDate = crDate;
		this.edDate = edDate;
		this.language = language;
		this.countries = countries;
		this.users = users;
		this.labelMLs = labelMLs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	@TlzHidden
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "langshort", nullable = false, length = 3)
	public String getLangshort() {
		return this.langshort;
	}

	public void setLangshort(String langshort) {
		this.langshort = langshort;
	}

	@Column(name = "langlong", nullable = false, length = 50)
	public String getLanglong() {
		return this.langlong;
	}

	public void setLanglong(String langlong) {
		this.langlong = langlong;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cr_date", nullable = false, length = 19)
	@NotNull
	public Date getCrDate() {
		return this.crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ed_date", length = 19)
	public Date getEdDate() {
		return this.edDate;
	}

	public void setEdDate(Date edDate) {
		this.edDate = edDate;
	}

	@Column(name = "language", length = 2)
	public String getLanguage() {
		return this.language;
	}

	public void setLanguage(String language) {
		this.language = language;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	@TlzHidden
	public Set<Country> getCountries() {
		return this.countries;
	}

	public void setCountries(Set<Country> countries) {
		this.countries = countries;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
//	@TlzHidden
	public Set<User> getUsers() {
		return this.users;
	}

	public void setUsers(Set<User> users) {
		this.users = users;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "language")
	@TlzHidden
	public Set<LabelML> getLabelMLs() {
		return this.labelMLs;
	}

	public void setLabelMLs(Set<LabelML> labelMLs) {
		this.labelMLs = labelMLs;
	}

	@Override
	@Transient
	public boolean hasLangDefined(String lang) {
		return true;
	}
	@Override
	@Transient
	public String getDisplayValue() {
		return getLanglong();
	}

	@Override
	@Transient
	public String getDisplayValue(String lang) {
		return getLanglong();
	}
	@Override
	@Transient
	public String getDefaultValue() {
		return getLanglong();
	}
	@Override
	@Transient
	@TlzHidden
	public Object getPK() {
		return id;
	}
	public String toString() {
		return getId() + ": " + getLangshort() + ", " + getLanglong() + ", " + getLanguage();
	}
}
