package db.entities;

// Generated 21 ��� 2012 12:09:39 �� by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.BatchSize;
import org.hibernate.annotations.Cache;
import org.hibernate.annotations.CacheConcurrencyStrategy;

/**
 * MethodSecurityLevelDef generated by hbm2java
 */
@Entity
@BatchSize(size=50)
@Cacheable
@Cache(usage = CacheConcurrencyStrategy.NONSTRICT_READ_WRITE)
@Table(name = "msecleveldefs")
public class MethodSecurityLevelDef implements java.io.Serializable {

	private MethodSecurityLevelDefId id;
	private User userByEdUserId;
	private User userByCrUserId;
	private Role role;
	private TypeClass typeClass;
	private String description;
	private Boolean allow;
	private Date crDate;
	private Date edDate;

	public MethodSecurityLevelDef() {
	}

	public MethodSecurityLevelDef(MethodSecurityLevelDefId id, Role role, TypeClass typeClass) {
		this.id = id;
		this.role = role;
		this.typeClass = typeClass;
	}

	public MethodSecurityLevelDef(MethodSecurityLevelDefId id, User userByEdUserId, User userByCrUserId, Role role, TypeClass typeClass,
			String description, Boolean allow, Date crDate, Date edDate) {
		this.id = id;
		this.userByEdUserId = userByEdUserId;
		this.userByCrUserId = userByCrUserId;
		this.role = role;
		this.typeClass = typeClass;
		this.description = description;
		this.allow = allow;
		this.crDate = crDate;
		this.edDate = edDate;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
			@AttributeOverride(name = "method", column = @Column(name = "method", nullable = false, length = 50)),
			@AttributeOverride(name = "classId", column = @Column(name = "class_id", nullable = false)) })
	public MethodSecurityLevelDefId getId() {
		return this.id;
	}

	public void setId(MethodSecurityLevelDefId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ed_user_id")
	public User getUserByEdUserId() {
		return this.userByEdUserId;
	}

	public void setUserByEdUserId(User userByEdUserId) {
		this.userByEdUserId = userByEdUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cr_user_id")
	public User getUserByCrUserId() {
		return this.userByCrUserId;
	}

	public void setUserByCrUserId(User userByCrUserId) {
		this.userByCrUserId = userByCrUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false, insertable = false, updatable = false)
	public TypeClass getTypeClass() {
		return this.typeClass;
	}

	public void setTypeClass(TypeClass typeClass) {
		this.typeClass = typeClass;
	}

	@Column(name = "description", length = 50)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "allow")
	public Boolean getAllow() {
		return this.allow;
	}

	public void setAllow(Boolean allow) {
		this.allow = allow;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cr_date", length = 19)
	public Date getCrDate() {
		return this.crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ed_date", length = 19)
	public Date getEdDate() {
		return this.edDate;
	}

	public void setEdDate(Date edDate) {
		this.edDate = edDate;
	}

}
