package db.entities;

// Generated 21 ��� 2012 12:09:39 �� by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * MethodSecurityLevelDefId generated by hbm2java
 */
@Embeddable
public class MethodSecurityLevelDefId implements java.io.Serializable {

	private int roleId;
	private String method;
	private int classId;

	public MethodSecurityLevelDefId() {
	}

	public MethodSecurityLevelDefId(int roleId, String method, int classId) {
		this.roleId = roleId;
		this.method = method;
		this.classId = classId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "method", nullable = false, length = 50)
	public String getMethod() {
		return this.method;
	}

	public void setMethod(String method) {
		this.method = method;
	}

	@Column(name = "class_id", nullable = false)
	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MethodSecurityLevelDefId))
			return false;
		MethodSecurityLevelDefId castOther = (MethodSecurityLevelDefId) other;

		return (this.getRoleId() == castOther.getRoleId())
				&& ((this.getMethod() == castOther.getMethod()) || (this.getMethod() != null && castOther.getMethod() != null && this.getMethod()
						.equals(castOther.getMethod()))) && (this.getClassId() == castOther.getClassId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + (getMethod() == null ? 0 : this.getMethod().hashCode());
		result = 37 * result + this.getClassId();
		return result;
	}

}
