package db.entities;

// Generated 17 ��� 2012 1:43:55 �� by Hibernate Tools 3.4.0.CR1

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Lob;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;

import org.apache.commons.lang.SerializationUtils;

/**
 * ObjectPk generated by hbm2java
 */
@Entity
@Table(name = "object_pk")
public class ObjectPk implements java.io.Serializable {

	private int id;
	private byte[] objectPk;
	private Set<ObjectSecurityLevelDef> objectSecurityLevelDefs = new HashSet<ObjectSecurityLevelDef>(0);

	public ObjectPk() {
	}

	public ObjectPk(int id) {
		this.id = id;
	}

	public ObjectPk(int id, byte[] objectPk, Set<ObjectSecurityLevelDef> objectSecurityLevelDefs) {
		this.id = id;
		this.objectPk = objectPk;
		this.objectSecurityLevelDefs = objectSecurityLevelDefs;
	}

	@Id
	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Lob
	@Column(name = "object_pk")
	public byte[] getObjectPk() {
		return this.objectPk;
	}
	@Transient
	public Object getPK() {
		return SerializationUtils.deserialize(getObjectPk());
	}

	public void setObjectPk(byte[] objectPk) {
		this.objectPk = objectPk;
	}
	public void setPK(Object pk) {
		this.objectPk = SerializationUtils.serialize((Serializable)pk);
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "objectPk")
	public Set<ObjectSecurityLevelDef> getObjectSecurityLevelDefs() {
		return this.objectSecurityLevelDefs;
	}

	public void setObjectSecurityLevelDefs(Set<ObjectSecurityLevelDef> objectSecurityLevelDefs) {
		this.objectSecurityLevelDefs = objectSecurityLevelDefs;
	}

}
