package db.entities;

// Generated 17 ��� 2012 1:43:55 �� by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ObjectSecurityLevelDefId generated by hbm2java
 */
@Embeddable
public class ObjectSecurityLevelDefId implements java.io.Serializable {

	private int roleId;
	private int classId;
	private int pkId;

	public ObjectSecurityLevelDefId() {
	}

	public ObjectSecurityLevelDefId(int roleId, int classId, int pkId) {
		this.roleId = roleId;
		this.classId = classId;
		this.pkId = pkId;
	}

	@Column(name = "role_id", nullable = false)
	public int getRoleId() {
		return this.roleId;
	}

	public void setRoleId(int roleId) {
		this.roleId = roleId;
	}

	@Column(name = "class_id", nullable = false)
	public int getClassId() {
		return this.classId;
	}

	public void setClassId(int classId) {
		this.classId = classId;
	}

	@Column(name = "pk_id", nullable = false)
	public int getPkId() {
		return this.pkId;
	}

	public void setPkId(int pkId) {
		this.pkId = pkId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ObjectSecurityLevelDefId))
			return false;
		ObjectSecurityLevelDefId castOther = (ObjectSecurityLevelDefId) other;

		return (this.getRoleId() == castOther.getRoleId()) && (this.getClassId() == castOther.getClassId())
				&& (this.getPkId() == castOther.getPkId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRoleId();
		result = 37 * result + this.getClassId();
		result = 37 * result + this.getPkId();
		return result;
	}

}
