package db.entities;

// Generated 17 ��� 2012 1:43:55 �� by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ObjectSecurityLevelDef generated by hbm2java
 */
@Entity
@Table(name = "osecleveldefs")
public class ObjectSecurityLevelDef implements java.io.Serializable {

	private ObjectSecurityLevelDefId id;
	private User userByEdUserId;
	private User userByCrUserId;
	private Role role;
	private TypeClass typeClass;
	private ObjectPk objectPk;
	private Boolean allow;
	private Date crDate;
	private Date edDate;

	public ObjectSecurityLevelDef() {
	}

	public ObjectSecurityLevelDef(ObjectSecurityLevelDefId id, Role role, TypeClass typeClass, ObjectPk objectPk) {
		this.id = id;
		this.role = role;
		this.typeClass = typeClass;
		this.objectPk = objectPk;
	}

	public ObjectSecurityLevelDef(ObjectSecurityLevelDefId id, User userByEdUserId, User userByCrUserId, Role role, TypeClass typeClass,
			ObjectPk objectPk, Boolean allow, Date crDate, Date edDate) {
		this.id = id;
		this.userByEdUserId = userByEdUserId;
		this.userByCrUserId = userByCrUserId;
		this.role = role;
		this.typeClass = typeClass;
		this.objectPk = objectPk;
		this.allow = allow;
		this.crDate = crDate;
		this.edDate = edDate;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false)),
			@AttributeOverride(name = "classId", column = @Column(name = "class_id", nullable = false)),
			@AttributeOverride(name = "pkId", column = @Column(name = "pk_id", nullable = false)) })
	public ObjectSecurityLevelDefId getId() {
		return this.id;
	}

	public void setId(ObjectSecurityLevelDefId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ed_user_id")
	public User getUserByEdUserId() {
		return this.userByEdUserId;
	}

	public void setUserByEdUserId(User userByEdUserId) {
		this.userByEdUserId = userByEdUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cr_user_id")
	public User getUserByCrUserId() {
		return this.userByCrUserId;
	}

	public void setUserByCrUserId(User userByCrUserId) {
		this.userByCrUserId = userByCrUserId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id", nullable = false, insertable = false, updatable = false)
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "class_id", nullable = false, insertable = false, updatable = false)
	public TypeClass getTypeClass() {
		return this.typeClass;
	}

	public void setTypeClass(TypeClass typeClass) {
		this.typeClass = typeClass;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pk_id", nullable = false, insertable = false, updatable = false)
	public ObjectPk getObjectPk() {
		return this.objectPk;
	}

	public void setObjectPk(ObjectPk objectPk) {
		this.objectPk = objectPk;
	}

	@Column(name = "allow")
	public Boolean getAllow() {
		return this.allow;
	}

	public void setAllow(Boolean allow) {
		this.allow = allow;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cr_date", length = 19)
	public Date getCrDate() {
		return this.crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ed_date", length = 19)
	public Date getEdDate() {
		return this.edDate;
	}

	public void setEdDate(Date edDate) {
		this.edDate = edDate;
	}

}
