package db.entities;

// Generated 21 ��� 2012 12:09:39 �� by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Session generated by hbm2java
 */
@Entity
@Table(name = "sessions")
public class Session implements java.io.Serializable {

	private SessionId id;
	private User user;
	private Date crDate;
	private String fromIp;
	private Date VDate;

	public Session() {
	}

	public Session(SessionId id, User user) {
		this.id = id;
		this.user = user;
	}

	public Session(SessionId id, User user, Date crDate, String fromIp) {
		this.id = id;
		this.user = user;
		this.crDate = crDate;
		this.fromIp = fromIp;
	}
	public Session(SessionId id, User user, Date crDate, String fromIp, Date VDate) {
		this.id = id;
		this.user = user;
		this.crDate = crDate;
		this.fromIp = fromIp;
		this.VDate = VDate;
	}

	@EmbeddedId
	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", nullable = false, length = 45)),
			@AttributeOverride(name = "userId", column = @Column(name = "user_id", nullable = false)) })
	public SessionId getId() {
		return this.id;
	}

	public void setId(SessionId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user_id", nullable = false, insertable = false, updatable = false)
	public User getUser() {
		return this.user;
	}

	public void setUser(User user) {
		this.user = user;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "cr_date", length = 19)
	public Date getCrDate() {
		return this.crDate;
	}

	public void setCrDate(Date crDate) {
		this.crDate = crDate;
	}

	@Column(name = "fromIP", length = 15)
	public String getFromIp() {
		return this.fromIp;
	}

	public void setFromIp(String fromIp) {
		this.fromIp = fromIp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "v_date", length = 19)
	public Date getVDate() {
		return this.VDate;
	}

	public void setVDate(Date VDate) {
		this.VDate = VDate;
	}
}
